import { useRouter } from "next/router";
import Head from "next/head";

import { useGetPersonByIdQuery, getRunningQueriesThunk } from "@/shared/api";
import { wrapper } from "@/shared/store";

import { Header } from "@/components/layout/Header";
import { Person } from "@/components/views/Person";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

const PersonPage = () => {
  const {
    query: { id },
  } = useRouter();

  const { data: person, isLoading } = useGetPersonByIdQuery(id);

  return (
    <>
      <Head>
        <title>KinoView {person && `- ${person?.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Person person={person} isLoading={isLoading} />
    </>
  );
};

export default PersonPage;
