import Head from "next/head";

import { wrapper } from "@/shared/store";
import { getRunningQueriesThunk } from "@/shared/api";

import { Home } from "@/components/views/Home";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

const HomePage = () => {
  return (
    <>
      <Head>
        <title>KinoView</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <Footer />
    </>
  );
};

export default HomePage;
