import Head from "next/head";
import { store, wrapper } from "@/store";
import { getRunningQueriesThunk } from "@/api";
import { Header } from "@/components/layout/Header";
import { Movies } from "@/components/views/Movies";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

const MoviesPage = () => {
  return (
    <>
      <Head>
        <title>KinoView</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Movies />
    </>
  );
};

export default MoviesPage;
