import {
  getMovieById,
  useGetMovieByIdQuery,
  useGetMoviesByIdQuery,
} from "@/shared/api";
import { useRouter } from "next/router";
import Head from "next/head";

import { wrapper } from "@/shared/store";
import { getRunningQueriesThunk } from "@/shared/api";

import { Movie } from "@/components/views/Movie";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const id = context.params?.id;
    store.dispatch(getMovieById.initiate(id));
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

const MoviePage = () => {
  const {
    query: { id },
  } = useRouter();

  const { data: movie } = useGetMovieByIdQuery(id);

  return (
    <>
      <Head>
        <title>KinoView {movie && `- ${movie.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Movie />
    </>
  );
};

export default MoviePage;
